### ISSUE TITLE
Trouble with signature when trying to interoperate with python

### ISSUE THREAD

**Issue by testlabauto** [hampuskraft/itsdangerous.js#1]
Any chance you can look at?:
https://stackoverflow.com/questions/77261475/converting-itsdangerous-python-code-to-javascript-using-itsdangerous-port

when I try to decrypt the javascript version using this python:
```
import sys
import hashlib
from itsdangerous import URLSafeTimedSerializer
from flask.sessions import TaggedJSONSerializer

def decode_flask_cookie(secret_key, encoded_cookie):
    salt = 'cookie-session'
    serializer = TaggedJSONSerializer()
    signer_kwargs = {
        'key_derivation': 'hmac',
        'digest_method': hashlib.sha1
    }
    s = URLSafeTimedSerializer(secret_key, salt=salt, serializer=serializer, signer_kwargs=signer_kwargs)
    
    try:
        cookie_dict = s.loads(encoded_cookie)
        return cookie_dict
    except Exception as e:
        # Handle any exceptions that may occur during decoding
        print(f"Error decoding cookie: {e}")
        return None

print(decode_flask_cookie(sys.argv[1], sys.argv[2]))
```

I get :
Error decoding cookie: Signature b'XnM2LujVtPpKnhWpt5FZwCPRSoY' does not match

**Comment by testlabauto** [comment]
It looks like this issue is the timestamp.  Here is an example of a getTimestamp that mimics the python:

```
 getTimestamp() {
        
        const time = Math.floor((new Date()).getTime() / 1000);
        const timeBuffer = Buffer.alloc(8);
        timeBuffer.writeBigUInt64BE(BigInt(time), 0);
        const timeBytes = timeBuffer.slice(timeBuffer.findIndex(b => b !== 0));
        const base64Url = base64url.encode(timeBytes).replace(/=+$/, '');
        console.log(`base64Url = ${base64Url}`);
        return base64Url;
    }
```

**Comment by hampuskraft** [comment]
Hi Christopher! Thanks for identifying the issue. I'll see if I can incorporate this in the code and improve the test coverage to ensure the timestamp signing behavior behaves like Python. It has been a while since I've maintained this repo, so I'll upgrade dependencies and configuration, as well, and release a new version.

**Comment by hampuskraft** [comment]
@testlabauto This should be solved as of https://github.com/hampuskraft/itsdangerous.js/commit/f314bcb8143b3810853cf9c11bbee1c61a788c72 (v1.0.1). Thanks!
